from commands.ALLESONGTEKSTENNL import main as songteksten
from commands.DATA import main as data
from commands.FEITEN import main as feiten
from commands.GAGILLEN import main as gillen
from commands.LANDEN import main as landen
from commands.PAASDAG import main as paasdag
from commands.TEKENCORONA import main as tekencorona
from commands.WEER import main as weer
from commands.WIEBENIK import main as wiebenik