files:
  - source: /teksten/nl/macallert.txt
    translation: /teksten/%two_letters_code%/%file_name%.%file_extension%
  - source: /teksten/nl/pakketinstall.txt
    translation: /teksten/%two_letters_code%/%file_name%.%file_extension%
  - source: /teksten/nl/pakketinstallsuc.txt
    translation: /teksten/%two_letters_code%/%file_name%.%file_extension%
  - source: /teksten/nl/prostart.txt
    translation: /teksten/%two_letters_code%/%file_name%.%file_extension%
