name: Terminal testen voor Linux

on: [push]

jobs:
  build-linux:
    runs-on: [ubuntu-latest, windows-latest, macOS-latest]

    steps:
    - uses: actions/checkout@v2
    - name: Set up Python 3.8
      uses: actions/setup-python@v2
      with:
        python-version: 3.8
    - run: apt install make
    - run: make terminal
